### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by magaton** [nicolewhite/neo4j-complaints#1]
Hello, files subissues.csv and subproducts.csv are missing. Where I can find them. In addition, the cql crashes with:

localhost:~/Servers/neo4j-community-2.2.2/bin$ neo4j-shell -host 127.0.0.1 -file ~/Projects/recommendation-engine/neo4j-complaints/LOAD_CSV.cql > ~/Projects/recommendation-engine/neo4j-complaints/result.log
ERROR (-v for expanded information):
    QueryExecutionKernelException: Cannot merge node using null property value for name

Any idea, how to debug this?
Thanks in advance

**Comment by nicolewhite** [comment]
Yeah, this repo accompanies a video where I create those files. I'll make some changes to this repo so that it can stand alone.

I'll try to recreate the .cql crash.

**Comment by magaton** [comment]
I watched the webinar. Very very useful, thanks. I think the problem is (with the latest csv file) that some of the Issues are blanks, so MERGE fails. You are addressing this problem with subproducts and subissues by composing new files. However I'd like to be able to do this on fly. Examine the row and call merge ONLY if particular column is not null. I know I can do this with WHERE clause after Load CSV, but  this is not good enough. Could you maybe suggest the way to do that? Thanks

**Comment by nicolewhite** [comment]
What's wrong with doing it in the WHERE clause? That's the change I was going to make.

**Comment by magaton** [comment]
Only that you need to do LOAD CSV multiple times for each of the columns you want to merge and where you expect empty values. What would be good, I think, is to do Merge(s) with condition (if not empty) within the single row read. I found FOREACH trick by Marak Needham explaining this: http://www.markhneedham.com/blog/2014/08/22/neo4j-load-csv-handling-empty-columns

**Comment by nicolewhite** [comment]
Yes, then you would need to use the FOREACH hack, unfortunately. I purposely avoided that in the webinar because it's pretty ugly.

**Comment by nicolewhite** [comment]
I've updated the repository to use `Consumer_Complaints.csv` across all the import queries. Also, I'm guessing your exception was raised because `LOAD_CSV.cql` requires the missing files you were asking about.
